apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: insipx
  template:
    metadata:
      labels:
        app: insipx
    spec:
      containers:
        - image: ghcr.io/insipx/website
          name: website
          ports:
            - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
